AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Amazon MQ for RabbitMQ Example
Globals:
    Function:
        Timeout: 3
Resources:
    MQConsumer:
        Type: AWS::Serverless::Function
        Properties:
            Handler: app.lambdaHandler
            Runtime: nodejs16.x
            Policies:
                - Version: '2012-10-17'
                  Statement:
                      - Effect: Allow
                        Resource: '*'
                        Action:
                            - mq:DescribeBroker
                            - secretsmanager:GetSecretValue
                            - ec2:CreateNetworkInterface
                            - ec2:DescribeNetworkInterfaces
                            - ec2:DescribeVpcs
                            - ec2:DeleteNetworkInterface
                            - ec2:DescribeSubnets
                            - ec2:DescribeSecurityGroups
            Events:
                MQEvent:
                    Type: MQ
                    Properties:
                        Broker: {{your amazon mq broker arn}}
                        Queues:
                            - test-msg
                        SourceAccessConfigurations:
                            - Type: BASIC_AUTH
                              URI: {{your secret manager arn}}
        Metadata: # Manage esbuild properties
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: 'es2020'
                Sourcemap: true
                EntryPoints:
                    - app.ts